### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/YACHT#15]
After @chunyuma 's recent bug fixing (yay!) it looks like something else might have been introduced:
```
$ /scratch2/dmk333/YACHT_tests/YACHT/run_YACHT.py --ref_matrix training_genomes_100_ani_0.999_ref_matrix_processed.npz --ani_thresh 0.999 --ksize 31 --sample_file /scratch2/cqm5886/YACHT-reproducibles/benchmark/CAMI_data/rhizosphere_data/sketches/rhimgCAMI2_sample_0.sig.zip --outfile rhimgCAMI2_sample_0_ani_0.999.csv


2023-09-08 10:57:56 - INFO - Loading reference matrix, hash to index dictionary, and organism data.
2023-09-08 10:58:24 - INFO - Loading sample signature.
2023-09-08 10:58:55 - INFO - Computing sample vector.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3749824/3749824 [00:05<00:00, 730935.27it/s]
Traceback (most recent call last):
  File "/scratch2/dmk333/YACHT_tests/YACHT/run_YACHT.py", line 85, in <module>
    sample_diff_idx = np.nonzero(recov_org_data['sample_scale_factor'] - recov_org_data['genome_scale_factor'])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in nonzero
  File "/home/faculty/dmk333/anaconda3/envs/yacht-repro/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 1984, in nonzero
    return _wrapfunc(a, 'nonzero')
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/anaconda3/envs/yacht-repro/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/anaconda3/envs/yacht-repro/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = wrap(result)
             ^^^^^^^^^^^^
  File "/home/faculty/dmk333/anaconda3/envs/yacht-repro/lib/python3.11/site-packages/pandas/core/generic.py", line 2107, in __array_wrap__
    return self._constructor(res, **d).__finalize__(self, method="__array_wrap__")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/anaconda3/envs/yacht-repro/lib/python3.11/site-packages/pandas/core/series.py", line 461, in __init__
    com.require_length_match(data, index)
  File "/home/faculty/dmk333/anaconda3/envs/yacht-repro/lib/python3.11/site-packages/pandas/core/common.py", line 571, in require_length_match
    raise ValueError(
ValueError: Length of values (1) does not match length of index (1388)
```

**Comment by dkoslicki** [comment]
Perhaps:
```
# check that the sample scale factor is the same as the genome scale factor for all organisms
    #print(f"sample_scale_factor: {recov_org_data['sample_scale_factor']}")
    #print(f"genome_scale_factor: {recov_org_data['genome_scale_factor']}")
    #print(recov_org_data['sample_scale_factor'] - recov_org_data['genome_scale_factor'])
    sample_diff_idx = np.where(recov_org_data['sample_scale_factor'].ne(recov_org_data['genome_scale_factor']))
    sample_diffs = recov_org_data['organism_name'].iloc[sample_diff_idx]
    if not sample_diffs.empty:
        raise ValueError(f'Sample scale factor does not equal genome scale factor for organism {sample_diffs.iloc[0]} and {len(sample_diffs) - 1} others.')
```

**Comment by chunyuma** [comment]
Problem is fixed. So I close this issue.
