### ISSUE TITLE
CAMI output format issue

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/YACHT#32]
When running the demo command (after installing the `taxdump` stuff), I get:
```bash
$ python ../srcs/standardize_yacht_output.py --yacht_output result.xlsx --sheet_name min_coverage0.2 --genome_to_taxid toy_genome_to_taxid.tsv --mode cami --sample_name 'MySample' --outfile_prefix cami_result --outdir ./
Traceback (most recent call last):
  File "/home/faculty/dmk333/YACHT/demo/../srcs/standardize_yacht_output.py", line 302, in <module>
    standardize_yacht_output.run(yacht_output_df, genome_to_taxid_df, outdir, outfile_prefix, 'cami', sample_name)
  File "/home/faculty/dmk333/YACHT/demo/../srcs/standardize_yacht_output.py", line 233, in run
    result = self.__to_cami(sample_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/YACHT/demo/../srcs/standardize_yacht_output.py", line 35, in __to_cami
    metadata_df = self.genome_to_taxid.merge(result[['TaxID','Rank','FullLineageTaxIDs','FullLineage','FullLineageRanks']], left_on='taxid', right_on='TaxID').drop(columns=['taxid']).reset_index(drop=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/frame.py", line 10490, in merge
    return merge(
           ^^^^^^
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 169, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 804, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1479, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on int64 and object columns for key 'taxid'. If you wish to proceed you should use pd.concat
```

**Comment by chunyuma** [comment]
It should be fixed now.

**Comment by dkoslicki** [comment]
fixed
