### ISSUE TITLE
Uncaught runtime error

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/YACHT#36]
```bash
:~/pycharm/YACHT/tests$ python ../make_training_data_from_sketches.py --ref_file testdata/20_genomes_sketches.zip --ksize 31 --prefix 20_genomes --outdir testdata/
2023-10-18 12:03:35 - INFO - Checking reference database file
2023-10-18 12:03:35 - INFO - Creating a temporary directory
2023-10-18 12:03:35 - INFO - Unzipping the sourmash signature file to the temporary directory
2023-10-18 12:03:35 - INFO - Extracting signature information
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 399457.52it/s]
2023-10-18 12:03:35 - INFO - Checking if all signatures have the same scaled
2023-10-18 12:03:35 - INFO - Find the close related genomes with ANI > ani_thresh from the reference database
2023-10-18 12:03:35 - INFO - Running sourmash multisearch with command: sourmash scripts multisearch /home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_sig_files.txt /home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_sig_files.txt -k 31 -s 1000 -c 16 -t 0.18351614317121134 -o /home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_multisearch_result.csv

== This is sourmash version 4.8.4. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

=> pyo3_branchwater 0.8.1; cite Irber et al., doi: 10.1101/2022.11.02.514947

ksize: 31 / scaled: 1000 / threshold: 0.18351614317121134
searching all sketches in '/home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_sig_files.txt' against '/home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_sig_files.txt' using 16 threads
Reading list of query paths from: '/home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_sig_files.txt'
Loaded 20 query signature(s)
Reading list of search paths from: '/home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_sig_files.txt'
Loaded 20 search signature(s)
Processed 0 comparisons
DONE. Processed 400 comparisons
...multisearch is done! results in '/home/faculty/dmk333/pycharm/YACHT/tests/testdata/20_genomes_intermediate_files/training_multisearch_result.csv'
0it [00:00, ?it/s]
2023-10-18 12:03:36 - INFO - Removing the close related organisms with ANI > ani_thresh
0it [00:00, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 210240.80it/s]
2023-10-18 12:03:36 - INFO - Writing out the manifest file
2023-10-18 12:03:36 - INFO - Writing out a mapping dataframe from representative organism to the close related organisms
Traceback (most recent call last):
  File "/home/faculty/dmk333/pycharm/YACHT/tests/../make_training_data_from_sketches.py", line 83, in <module>
    rep_remove_df.columns = ['rep_org', 'corr_orgs']
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements
```

**Comment by chunyuma** [comment]
@dkoslicki, it should be fixed now. Please try it again and let me know if it doesn't work.

**Comment by dkoslicki** [comment]
fixed
