### ISSUE TITLE
bug: `os.exit`

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/YACHT#86]
Pretty sure it should be `sys.exit`

**Comment by dkoslicki** [comment]
```
yacht download pretrained_ref_db --database gtdb --db_version rs214 --k 31 --ani_thresh 0.995 --outfolder .

$ yacht download pretrained_ref_db --database gtdb --db_version rs214 --k 31 --ani_thresh 0.995 --outfolder .
2023-12-13 13:41:25 - INFO - Fetching list of files from Zenodo community 'yacht'
2023-12-13 13:41:26 - ERROR - No pretrained database found for gtdb-rs214-reps.k31_0.995_pretrained.zip on Zenodo. We currenlty only support [0.8, 0.9995] for gtdb-rs214-reps.k31.
Traceback (most recent call last):
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/bin/yacht", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/yacht/__init__.py", line 51, in main
    args.func(args)
  File "/home/faculty/dmk333/miniforge3/envs/yacht_env/lib/python3.12/site-packages/yacht/download_pretrained_ref_db.py", line 105, in main
    os.exit(1)
```
